// ─────────────────────────────────────────────────────────────────────────────
//  DATA — loaded via fetch() from data/clean/ (generated by normalize_data.py)
//
//  Why fetch() instead of embedding:
//  Updating prices means running normalize_data.py and refreshing — no HTML
//  edits required. The pipeline and the app are properly decoupled.
//
//  Fallback: if the fetch fails (e.g., opened as a local file without a server),
//  we show a helpful error rather than a blank screen.
// ─────────────────────────────────────────────────────────────────────────────

let CUSTOMERS = [];
let EQUIPMENT = [];
let LABOR = [];
let META = null;

const MARGIN_OVERRIDES = {
  standard:   1.0,   
  preferred:  0.90,  
  commercial: 0.87,  
};

const TAX_RATE = 0.0975;
const DRAFT_KEY = 'hvac_estimator_draft';
const HISTORY_KEY = 'hvac_estimator_history';

// ─────────────────────────────────────────────────────────────────────────────
//  STATE
// ─────────────────────────────────────────────────────────────────────────────
const state = {
  cust: null,
  eCart: {},         // { equipId: qty }
  lCart: {},         // { laborId: hours }
  activeCat: 'all',
  notes: '',
  marginTier: 'standard',
};

// ─────────────────────────────────────────────────────────────────────────────
//  UTILS
// ─────────────────────────────────────────────────────────────────────────────
const $ = id => document.getElementById(id);
const fmt = n => '$' + Math.round(n).toLocaleString();
const fmtDate = d => d
  ? new Date(d + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  : '—';
const fmtDateTime = iso => new Date(iso).toLocaleString('en-US', {
  month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit'
});

function highlight(text, query) {
  if (!query || !text) return text || '';
  const str = String(text);
  
  // try direct match first
  const re = new RegExp('(' + query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'gi');
  if (re.test(str)) return str.replace(re, '<mark>$1</mark>');
  
  // if query is all digits, try matching against stripped version
  const digits = query.replace(/\D/g, '');
  if (!digits) return str;
  const strippedText = str.replace(/\D/g, '');
  const idx = strippedText.indexOf(digits);
  if (idx === -1) return str;
  
  // find the corresponding position in the original formatted string
  let digitCount = 0;
  let start = -1, end = -1;
  for (let i = 0; i < str.length; i++) {
    if (/\d/.test(str[i])) {
      if (digitCount === idx) start = i;
      if (digitCount === idx + digits.length - 1) { end = i + 1; break; }
      digitCount++;
    }
  }
  if (start === -1 || end === -1) return str;
  return str.slice(0, start) + '<mark>' + str.slice(start, end) + '</mark>' + str.slice(end);
}

function retailPrice(equip) {
  // _retailPrice is computed by the pipeline with per-category markup.
  // We then apply the selected margin tier multiplier on top.
  const base = equip._retailPrice || equip.baseCost || 0;
  const multiplier = MARGIN_OVERRIDES[state.marginTier] || 1.0;
  return Math.round(base * multiplier);
}

// ─────────────────────────────────────────────────────────────────────────────
//  DATA LOADING
// ─────────────────────────────────────────────────────────────────────────────
async function loadData() {
  try {
    const [customers, equipment, labor, meta] = await Promise.all([
      fetch('data/clean/customers.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
      fetch('data/clean/equipment.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
      fetch('data/clean/labor_rates.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
      fetch('data/clean/meta.json').then(r => { if (!r.ok) throw new Error(r.status); return r.json(); }),
    ]);

    CUSTOMERS = customers;
    EQUIPMENT = equipment;
    LABOR = labor.map(l => ({
      id: `${l.jobType}/${l.level}`,
      job: l.jobType.charAt(0).toUpperCase() + l.jobType.slice(1),
      level: l.level.charAt(0).toUpperCase() + l.level.slice(1),
      rate: l.hourlyRate,
      min: l.estimatedHours ? l.estimatedHours.min : undefined,
      max: l.estimatedHours ? l.estimatedHours.max : undefined,
      midpoint: l._midpointHours,
    }));
    META = meta;

    showFreshnessBadge(meta);
    onDataLoaded();

  } catch (err) {
    $('view-loading').innerHTML = `
      <div class="load-error">
        <strong>Could not load catalog data</strong>
        Run <code>python normalize_data.py</code> first to generate
        <code>data/clean/</code>, then serve this file over HTTP
        (e.g. <code>python -m http.server 8000</code>).
        <br><br>Error: ${err.message}
      </div>`;
  }
}

function showFreshnessBadge(meta) {
  if (!meta || !meta.normalizedAt) return;
  const updated = new Date(meta.normalizedAt);
  const ageHours = (Date.now() - updated) / 36e5;
  const badge = $('freshness-badge');
  badge.style.display = 'block';
  if (ageHours > 168) { // > 1 week
    badge.textContent = `catalog: ${Math.floor(ageHours / 24)}d old`;
    badge.classList.add('stale');
    badge.title = 'Catalog may be outdated. Re-run normalize_data.py to refresh.';
  } else {
    badge.textContent = `catalog: ${fmtDate(meta.normalizedAt.split('T')[0])}`;
  }
}

function onDataLoaded() {
  $('view-loading').style.display = 'none';
  buildCatTabs();
  renderCustomers(); 
  checkForDraft();
  showView('estimate');
}

// ─────────────────────────────────────────────────────────────────────────────
//  VIEW SWITCHING
// ─────────────────────────────────────────────────────────────────────────────
function showView(v) {
  ['estimate', 'history', 'loading'].forEach(name => {
    $(`view-${name}`).style.display = name === v ? 'block' : 'none';
  });
  $('tab-estimate').classList.toggle('active', v === 'estimate');
  $('tab-history').classList.toggle('active', v === 'history');
  if (v === 'history') renderHistory();
}

// ─────────────────────────────────────────────────────────────────────────────
//  DRAFT PERSISTENCE (localStorage)
//
//  Why localStorage over a backend:
//  For this stage, we want zero infrastructure. localStorage gives us
//  crash recovery (tab close, accidental refresh) for free. The tradeoff
//  is that drafts don't sync across devices — acceptable for a single-tech
//  workflow where each person owns their own phone.
// ─────────────────────────────────────────────────────────────────────────────
function saveDraft() {
  if (!state.cust) return; // nothing worth saving yet
  const draft = {
    custId: state.cust.id,
    eCart: state.eCart,
    lCart: state.lCart,
    notes: $('tech-notes') ? $('tech-notes').value : '',
    marginTier: state.marginTier,
    savedAt: new Date().toISOString(),
  };
  try {
    localStorage.setItem(DRAFT_KEY, JSON.stringify(draft));
    flashSaved();
  } catch (e) { /* storage full or private mode */ }
}

function flashSaved() {
  const dot = $('saved-dot');
  dot.classList.add('show');
  setTimeout(() => dot.classList.remove('show'), 1500);
}

function checkForDraft() {
  try {
    const raw = localStorage.getItem(DRAFT_KEY);
    if (!raw) return;
    const draft = JSON.parse(raw);
    const cust = CUSTOMERS.find(c => c.id === draft.custId);
    if (!cust) return;
    const banner = $('draft-banner');
    $('draft-banner-text').textContent =
      `Unsaved draft for ${cust.name} from ${fmtDateTime(draft.savedAt)}. Restore?`;
    banner.style.display = 'flex';
  } catch (e) {}
}

function restoreDraft() {
  try {
    const draft = JSON.parse(localStorage.getItem(DRAFT_KEY));
    const cust = CUSTOMERS.find(c => c.id === draft.custId);
    if (!cust) return;
    selectCustomer(cust.id);
    state.eCart = draft.eCart || {};
    state.lCart = draft.lCart || {};
    state.marginTier = draft.marginTier || 'standard';
    if ($('margin-select')) $('margin-select').value = state.marginTier;
    $('draft-banner').style.display = 'none';
    goStep(4);
  } catch (e) {}
}

function clearDraft() {
  localStorage.removeItem(DRAFT_KEY);
  $('draft-banner').style.display = 'none';
}

function dismissDraft() {
  clearDraft();
}

// ─────────────────────────────────────────────────────────────────────────────
//  QUOTE HISTORY (localStorage)
// ─────────────────────────────────────────────────────────────────────────────
function getHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY)) || []; }
  catch (e) { return []; }
}

function saveToHistory(entry) {
  const history = getHistory();
  history.unshift(entry); // newest first
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 100))); }
  catch (e) {}
}

function renderHistory() {
  const history = getHistory();
  const el = $('history-list');
  if (!history.length) {
    el.innerHTML = `<div class="history-empty">📋<p>No quotes saved yet.<br>Finalize a quote to see it here.</p></div>`;
    return;
  }
  el.innerHTML = history.map((q, i) => `
    <div class="h-card">
      <div class="h-card-top">
        <div>
          <div class="h-customer">${q.customerName}</div>
          <div class="h-items">${q.itemSummary}</div>
        </div>
        <div style="text-align:right">
          <div class="h-total">${fmt(q.total)}</div>
          <div class="h-time">${fmtDateTime(q.savedAt)}</div>
        </div>
      </div>
      <div class="h-actions">
        <button class="h-btn" onclick="showHistoryQuote(${i})">View quote</button>
        <button class="h-btn danger" onclick="deleteHistoryEntry(${i})">Delete</button>
      </div>
    </div>`).join('');
}

function showHistoryQuote(i) {
  const entry = getHistory()[i];
  if (!entry) return;
  $('quote-text-content').textContent = entry.quoteText;
  $('modal').classList.add('open');
}

function deleteHistoryEntry(i) {
  const history = getHistory();
  history.splice(i, 1);
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(history)); } catch (e) {}
  renderHistory();
}

function clearHistory() {
  $('clear-history-modal').classList.add('open');
}

function executeHardClearHistory() {
  $('clear-history-modal').classList.remove('open');
  localStorage.removeItem(HISTORY_KEY);
  renderHistory();
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP NAVIGATION
// ─────────────────────────────────────────────────────────────────────────────
function goStep(n) {
  [1, 2, 3, 4].forEach(i => {
    $('step' + i).style.display = i === n ? 'block' : 'none';
    const btn = $('sn' + i);
    // Mark customer step red if navigating past it without a selection
    if (i === 1 && i !== n && !state.cust) {
      btn.className = 'step-btn required';
    } else {
      btn.className = 'step-btn' + (i === n ? ' active' : i < n ? ' done' : '');
    }
  });
  if (n === 2) renderEquip();
  if (n === 3) renderLabor();
  if (n === 4) { renderQuote(); if ($('margin-select')) $('margin-select').value = state.marginTier; }
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP 1 – CUSTOMERS
// ─────────────────────────────────────────────────────────────────────────────
function renderCustomers() {
  const q = ($('csearch').value || '').toLowerCase().trim();
  const digits = q.replace(/\D/g, '');

  const matchesPhone = c =>
    digits.length > 0 &&
    (c.phone || '').replace(/\D/g, '').includes(digits);

  const list = CUSTOMERS
    .filter(c =>
      !q ||
      c.name.toLowerCase().includes(q) ||
      c.address.toLowerCase().includes(q) ||
      matchesPhone(c)
    )
    .sort((a, b) => {
      if (!q) return 0;
      const aName = a.name.toLowerCase();
      const bName = b.name.toLowerCase();
      // Exact name match first
      if (aName === q) return -1;
      if (bName === q) return 1;
      // Name starts with query next
      if (aName.startsWith(q) && !bName.startsWith(q)) return -1;
      if (bName.startsWith(q) && !aName.startsWith(q)) return 1;
      // Name contains query before address match
      const aNameMatch = aName.includes(q);
      const bNameMatch = bName.includes(q);
      if (aNameMatch && !bNameMatch) return -1;
      if (bNameMatch && !aNameMatch) return 1;
      return 0;
    });

  $('clist').innerHTML = list.length
    ? list.map(c => {
        const isSel = state.cust?.id === c.id;
        return `<div class="c-card${isSel ? ' selected' : ''}" onclick="selectCustomer('${c.id}')">
          <div class="c-name">
            ${highlight(c.name, q)}
            ${c.propertyType === 'commercial' ? '<span class="badge badge-comm">commercial</span>' : ''}
            ${(c.systemAge || 0) >= 15 ? `<span class="badge badge-old">system: ${c.systemAge}yr</span>` : ''}
          </div>
          <div class="c-detail">${highlight(c.address, q)}</div>
          <div class="c-detail">${highlight(c.phone || 'no phone on file', q)} · ${c.systemType || '—'}</div>
        </div>`;
      }).join('')
    : '<div class="empty-state">No customers found</div>';
}

function selectCustomer(id) {
  state.cust = CUSTOMERS.find(c => c.id === id);
  renderCustomers();
  $('cdetail-panel').style.display = 'block';

  const c = state.cust;
  const sqft = (c.squareFootage || c.sqft || 0).toLocaleString();
  const warnHtml = (c.systemAge || 0) >= 15
    ? `<div class="warn-box">⚠️ System is ${c.systemAge} years old — worth discussing system health on this visit.</div>`
    : '';

  $('cdetail').innerHTML = `
    <div class="prop-grid">
      <div class="prop-box"><div class="prop-label">System</div><div class="prop-val">${c.systemType || '—'}</div></div>
      <div class="prop-box"><div class="prop-label">Property</div><div class="prop-val" style="text-transform:capitalize">${c.propertyType || '—'} · ${sqft} sq ft</div></div>
      <div class="prop-box"><div class="prop-label">System age</div><div class="prop-val">${c.systemAge != null ? c.systemAge + ' years' : 'Unknown'}</div></div>
      <div class="prop-box"><div class="prop-label">Last service</div><div class="prop-val">${fmtDate(c.lastServiceDate)}</div></div>
    </div>${warnHtml}`;

  $('btn-next1').disabled = false;
  $('sn1').classList.remove('required');
  saveDraft();
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP 2 – EQUIPMENT
// ─────────────────────────────────────────────────────────────────────────────
function scrollCats(dir) {
  const el = $('cat-tabs');
  el.scrollBy({ left: dir * 120, behavior: 'smooth' });
  setTimeout(updateCatArrows, 150);
}
 
function updateCatArrows() {
  const el = $('cat-tabs');
  if (!el) return;
  const atStart = el.scrollLeft <= 4;
  const atEnd = el.scrollLeft + el.clientWidth >= el.scrollWidth - 4;
  $('cat-left').classList.toggle('hidden', atStart);
  $('cat-right').classList.toggle('hidden', atEnd);
}
function buildCatTabs() {
  const cats = ['all', ...new Set(EQUIPMENT.map(e => e.category))].sort(
    (a, b) => a === 'all' ? -1 : b === 'all' ? 1 : a.localeCompare(b)
  );
  $('cat-tabs').innerHTML = cats.map(c =>
    `<button class="cat-pill${c === 'all' ? ' active' : ''}" onclick="setCat('${c}', this)">${c === 'all' ? 'All items' : c}</button>`
  ).join('');
}

function setCat(c, el) {
  state.activeCat = c;
  document.querySelectorAll('.cat-pill').forEach(p => p.classList.remove('active'));
  el.classList.add('active');
  renderEquip();
}

function renderEquip() {
  const esearchEl = $('esearch');
  const q = ((esearchEl && esearchEl.value) || '').toLowerCase().trim();
  const list = EQUIPMENT.filter(e =>
    (state.activeCat === 'all' || e.category === state.activeCat) &&
    (!q || e.name.toLowerCase().includes(q) || e.brand.toLowerCase().includes(q) || (e.modelNumber || '').toLowerCase().includes(q))
  );

  $('elist').innerHTML = list.length
    ? list.map(e => {
        const qty = state.eCart[e.id] || 0;
        const price = retailPrice(e);
        return `<div class="e-row">
          <div class="e-info">
            <div class="e-name">${highlight(e.name, q)}</div>
            <div class="e-meta">${highlight(e.brand, q)} · ${highlight(e.modelNumber || '—', q)}</div>
          </div>
          <div class="e-price">${fmt(price)}</div>
          ${qty
            ? `<div class="qty-wrap">
                <button class="qty-btn" onclick="chgE('${e.id}',-1)">−</button>
                <span class="qty-num">${qty}</span>
                <button class="qty-btn" onclick="chgE('${e.id}',1)">+</button>
               </div>`
            : `<button class="add-btn" onclick="chgE('${e.id}',1)" title="Add">+</button>`}
        </div>`;
      }).join('')
    : '<div class="empty-state">No items match</div>';
}

function chgE(id, delta) {
  const n = Math.max(0, (state.eCart[id] || 0) + delta);
  if (!n) delete state.eCart[id]; else state.eCart[id] = n;
  renderEquip();
  saveDraft();
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP 3 – LABOR
// ─────────────────────────────────────────────────────────────────────────────
function renderLabor() {
  $('llist').innerHTML = LABOR.map(l => {
    const hrs = state.lCart[l.id] || '';
    const total = (parseFloat(hrs) || 0) * l.rate;
    return `<div class="l-row">
      <div class="l-info">
        <div class="l-name">${l.job} — ${l.level}</div>
        <div class="l-rate">${fmt(l.rate)} / hr</div>
        ${l.min != null ? `<div class="l-range">typical: ${l.min}–${l.max} hrs</div>` : ''}
        <div class="l-hrs-wrap">
          <span class="l-hrs-label">Hours:</span>
          <button class="qty-btn" onclick="setHrs('${l.id}', Math.max(0, (parseFloat(state.lCart['${l.id}'] || 0) - 0.5)), null)">−</button>
          <input type="number" class="hrs-input" value="${hrs}" min="0" ${l.max != null ? `max="${l.max}"` : ''} step="0.5" readonly>
          <button class="qty-btn" onclick="setHrs('${l.id}', Math.min(${l.max ?? 99}, (parseFloat(state.lCart['${l.id}'] || 0) + 0.5)), null)">+</button>
        </div>
      </div>
      <div class="l-total" id="lt-${l.id.replace('/', '-')}">${total > 0 ? fmt(total) : ''}</div>
    </div>`;
  }).join('');
}

function setHrs(id, val, el) {
  const num = Math.round(parseFloat(val) * 2) / 2; 
  state.lCart[id] = num > 0 ? num : '';
  if (num <= 0) {
    delete state.lCart[id];  
  } else {
    state.lCart[id] = num;
  }
  saveDraft();
  if (!el) renderLabor();
  
  // update total display
  const labor = LABOR.find(l => l.id === id);
  if (labor) {
    const total = (parseFloat(state.lCart[id]) || 0) * labor.rate;
    const el2 = document.getElementById('lt-' + id.replace('/', '-'));
    if (el2) el2.textContent = total > 0 ? fmt(total) : '';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP 4 – QUOTE
// ─────────────────────────────────────────────────────────────────────────────
function calcTotals() {
  let parts = 0, labor = 0;
  Object.entries(state.eCart).forEach(([id, qty]) => {
    const e = EQUIPMENT.find(x => x.id === id);
    if (e) parts += retailPrice(e) * qty;
  });
  Object.entries(state.lCart).forEach(([id, hrs]) => {
    const l = LABOR.find(x => x.id === id);
    if (l) labor += l.rate * hrs;
  });
  return { parts, labor, sub: parts + labor };
}

function renderQuote() {
  const marginEl = $('margin-select');
  state.marginTier = (marginEl && marginEl.value) || 'standard';
  const { parts, labor, sub } = calcTotals();
  const tax = sub * TAX_RATE;
  const total = sub + tax;

  $('m-parts').textContent = fmt(parts);
  $('m-labor').textContent = fmt(labor);
  $('m-total').textContent = fmt(total);

  const lines = [];
  Object.entries(state.eCart).forEach(([id, qty]) => {
    const e = EQUIPMENT.find(x => x.id === id);
    if (e) lines.push({ name: e.name, sub: `${e.brand} · ${e.modelNumber} × ${qty}`, amt: retailPrice(e) * qty, type: 'e', id });
  });
  Object.entries(state.lCart).forEach(([id, hrs]) => {
    const l = LABOR.find(x => x.id === id);
    if (l) lines.push({ name: `${l.job} — ${l.level}`, sub: `${hrs} hr${hrs !== 1 ? 's' : ''} @ ${fmt(l.rate)}/hr`, amt: l.rate * hrs, type: 'l', id });
  });

  $('qlines').innerHTML = lines.length
    ? lines.map(ln => `<div class="q-line">
        <div style="flex:1;min-width:0">
          <div class="q-name">${ln.name}</div>
          <div class="q-sub">${ln.sub}</div>
        </div>
        <div class="q-amt">${fmt(ln.amt)}</div>
        <button class="rm-btn" onclick="rmLine('${ln.type}','${ln.id}')">×</button>
      </div>`).join('')
    : '<div class="empty-state">No items — go back to add equipment or labor</div>';

  const tierLabels = { standard: 'Standard', preferred: 'Preferred (10%)', commercial: 'Commercial (13%)' };

  $('qtotals').innerHTML = `
    <div class="totals-row"><span>Parts markup tier</span><span style="font-size:12px;color:var(--gray-500)">${tierLabels[state.marginTier]}</span></div>
    <div class="totals-row"><span>Subtotal</span><span>${fmt(sub)}</span></div>
    <div class="totals-row"><span>Tax (9.75% IL)</span><span>${fmt(tax)}</span></div>
    <div class="totals-row grand"><span>Total</span><span>${fmt(total)}</span></div>`;
}

function rmLine(type, id) {
  if (type === 'e') delete state.eCart[id]; else delete state.lCart[id];
  renderQuote();
  saveDraft();
}

// ─────────────────────────────────────────────────────────────────────────────
//  QUOTE TEXT OUTPUT
// ─────────────────────────────────────────────────────────────────────────────
function buildQuoteText() {
  const { parts, labor, sub } = calcTotals();
  const tax = sub * TAX_RATE;
  const c = state.cust;
  const tierLabels = { standard: 'Standard', preferred: 'Preferred customer', commercial: 'Commercial contract' };

  let txt = `═══════════════════════════════════════\n`;
  txt += `  SERVICE ESTIMATE\n`;
  txt += `═══════════════════════════════════════\n`;
  txt += `Date:     ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}\n`;
  txt += `Customer: ${c.name}\n`;
  txt += `Address:  ${c.address}\n`;
  if (c.phone) txt += `Phone:    ${c.phone}\n`;
  txt += `Pricing:  ${tierLabels[state.marginTier]}\n\n`;

  const equipLines = Object.entries(state.eCart).map(([id, qty]) => {
    const e = EQUIPMENT.find(x => x.id === id);
    return e ? { name: e.name, detail: `${e.brand} #${e.modelNumber}`, qty, total: retailPrice(e) * qty } : null;
  }).filter(Boolean);

  const laborLines = Object.entries(state.lCart).map(([id, hrs]) => {
    const l = LABOR.find(x => x.id === id);
    return l ? { name: `${l.job} — ${l.level}`, detail: `${hrs} hr @ $${l.rate}/hr`, total: l.rate * hrs } : null;
  }).filter(Boolean);

  if (equipLines.length) {
    txt += `EQUIPMENT & PARTS\n`;
    txt += `───────────────────────────────────────\n`;
    equipLines.forEach(e => {
      txt += `${e.name}\n  ${e.detail}${e.qty > 1 ? ` × ${e.qty}` : ''}  .....  ${fmt(e.total)}\n`;
    });
    txt += `\n`;
  }

  if (laborLines.length) {
    txt += `LABOR\n`;
    txt += `───────────────────────────────────────\n`;
    laborLines.forEach(l => {
      txt += `${l.name}\n  ${l.detail}  .....  ${fmt(l.total)}\n`;
    });
    txt += `\n`;
  }

  const notesEl = $('tech-notes');
  const notes = notesEl && notesEl.value ? notesEl.value.trim() : '';
  if (notes) { txt += `NOTES\n───────────────────────────────────────\n${notes}\n\n`; }

  txt += `═══════════════════════════════════════\n`;
  txt += `  Subtotal    ${fmt(sub).padStart(8)}\n`;
  txt += `  Tax (9.75%) ${fmt(tax).padStart(8)}\n`;
  txt += `  ─────────────────────────\n`;
  txt += `  TOTAL       ${fmt(sub + tax).padStart(8)}\n`;
  txt += `═══════════════════════════════════════\n`;
  txt += `\nThank you for choosing us for your HVAC needs.\n`;
  return txt;
}

function showQuoteModal() {
  if (!state.cust) {
    $('no-customer-modal').classList.add('open');    
    return;
  }
  $('quote-text-content').textContent = buildQuoteText();
  $('modal').classList.add('open');
}

function closeModal() { $('modal').classList.remove('open'); }

function copyFromModal() {
  navigator.clipboard.writeText(buildQuoteText()).catch(() => {});
  const btn = $('modal-copy-btn');
  btn.textContent = 'Copied!';
  setTimeout(() => btn.textContent = 'Copy to clipboard', 2000);
}

function printQuote() {
  const titleName = state.cust ? state.cust.name : 'Estimate';
  const styles = "body{font-family:'Courier New',monospace;font-size:13px;padding:40px;white-space:pre-wrap;color:#111}";
  const body = buildQuoteText()
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const html =
    '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Estimate - ' +
    titleName +
    '</title><style>' +
    styles +
    '</style></head><body>' +
    body +
    '</' + 'body></' + 'html>';

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

// ─────────────────────────────────────────────────────────────────────────────
//  FINALIZE — saves to history and clears draft
// ─────────────────────────────────────────────────────────────────────────────
function finalizeQuote() {
  if (!state.cust) {
    $('no-customer-modal').classList.add('open');    
    return;
  }
  
  const { sub } = calcTotals();
  const tax = sub * TAX_RATE;

  const itemParts = Object.entries(state.eCart).map(([id, qty]) => {
    const e = EQUIPMENT.find(x => x.id === id);
    return e ? `${e.name}${qty > 1 ? ' ×' + qty : ''}` : null;
  }).filter(Boolean);
  const itemLabor = Object.entries(state.lCart).map(([id, hrs]) => {
    const l = LABOR.find(x => x.id === id);
    return l ? `${l.job} (${hrs}hr)` : null;
  }).filter(Boolean);
  const allItems = [...itemParts, ...itemLabor];

  const entry = {
    customerName: state.cust.name,
    customerAddress: state.cust.address,
    total: sub + tax,
    itemSummary: allItems.slice(0, 3).join(', ') + (allItems.length > 3 ? ` +${allItems.length - 3} more` : ''),
    marginTier: state.marginTier,
    quoteText: buildQuoteText(),
    savedAt: new Date().toISOString(),
  };

  saveToHistory(entry);
  clearDraft();

  // Flash the history tab
  const dot = $('saved-dot');
  dot.classList.add('show');

  const btn = $('finalize-btn');
  btn.textContent = '✓ Saved!';
  btn.disabled = true;
  
  setTimeout(() => {
    dot.classList.remove('show');
    btn.textContent = 'Save & finalize';
    btn.disabled = false;
    state.cust = null;
    state.eCart = {};
    state.lCart = {};
    state.marginTier = 'standard';
    $('tech-notes').value = '';
    $('csearch').value = '';
    $('cdetail-panel').style.display = 'none';  
    $('btn-next1').disabled = true;           
    renderCustomers();                          
    showView('estimate');
    goStep(1);
  }, 1500);
}

function confirmClearQuote() {
  $('clear-modal').classList.add('open');
}

function executeClearQuote() {
  $('clear-modal').classList.remove('open');
  state.cust = null;
  state.eCart = {};
  state.lCart = {};
  state.marginTier = 'standard';
  $('tech-notes').value = '';
  $('csearch').value = '';
  clearDraft();
  goStep(1);
}


// ─────────────────────────────────────────────────────────────────────────────
//  BOOT
// ─────────────────────────────────────────────────────────────────────────────
$('modal').addEventListener('click', e => { if (e.target === $('modal')) closeModal(); });
$('clear-modal').addEventListener('click', e => { 
  if (e.target === $('clear-modal')) $('clear-modal').classList.remove('open'); 
});
$('clear-history-modal').addEventListener('click', e => { if (e.target === $('clear-history-modal')) $('clear-history-modal').classList.remove('open'); });
loadData();